export interface PolicyTemplateRecord {
  key: string;
  name: string;
  format: "markdown" | "html" | "text";
  body: string;
}

const SOC2_TEMPLATE: PolicyTemplateRecord = {
  key: "soc2.demo",
  name: "SOC 2 Access Control Policy (Demo)",
  format: "markdown",
  body: [
    "# SOC 2 Access Control Policy",
    "",
    "**Tenant:** {{tenantId}}",
    "",
    "**Generated:** {{generatedAt}}",
    "",
    "## Purpose",
    "This policy documents the access control principles adopted by {{tenantId}} to satisfy SOC 2 common criteria for logical access.",
    "",
    "## Scope",
    "- Workforce members with access to production data",
    "- Third-party vendors operating on behalf of {{tenantId}}",
    "- Supporting infrastructure and SaaS services",
    "",
    "## Roles & Responsibilities",
    "- **Policy Owner:** Security Team ({{input.contactEmail}})",
    "- **Approver:** Chief Technology Officer",
    "- **Review Cadence:** Quarterly with ad-hoc updates following significant changes",
    "",
    "## Controls",
    "1. **Account Provisioning**",
    "   - Joiner workflows are initiated within 24 hours of hire confirmation.",
    "   - Access requests are logged and approved by the hiring manager.",
    "2. **Account Reviews**",
    "   - Access is reviewed every 90 days for relevance and least privilege.",
    "   - Reports of inactive accounts over 30 days are generated and remediated.",
    "3. **Account Revocation**",
    "   - Offboarding (leaver) workflows disable primary accounts within 4 hours.",
    "   - Shared credentials are rotated when a user departs.",
    "",
    "## Additional Context",
    "{{input.summary}}",
    "",
    "---",
    "*This document was generated deterministically by AtlasIT compliance automation.*",
    "",
  ].join("\n"),
};

const ISO27001_TEMPLATE: PolicyTemplateRecord = {
  key: "iso27001.isms",
  name: "ISO 27001 Information Security Management Policy",
  format: "markdown",
  body: [
    "# ISO 27001 Information Security Management Policy",
    "",
    "**Tenant:** {{tenantId}}",
    "",
    "**Generated:** {{generatedAt}}",
    "",
    "## Purpose",
    "This policy establishes the Information Security Management System (ISMS) framework for {{tenantId}} in accordance with ISO/IEC 27001:2022.",
    "",
    "## Scope",
    "- All information assets owned, operated, or managed by {{tenantId}}",
    "- Personnel, contractors, and third parties with access to organizational information",
    "- Physical and logical infrastructure supporting information processing",
    "",
    "## Information Security Objectives",
    "- **Confidentiality:** Ensure information is accessible only to authorized individuals",
    "- **Integrity:** Safeguard the accuracy and completeness of information",
    "- **Availability:** Ensure authorized users have timely access to information",
    "",
    "## Roles & Responsibilities",
    "- **Information Security Officer:** {{input.contactEmail}}",
    "- **Risk Owner:** Department heads responsible for assets within their domain",
    "- **ISMS Committee:** Reviews policy quarterly and after significant incidents",
    "",
    "## Controls",
    "1. **Asset Management (A.8)**",
    "   - Maintain an inventory of all information assets with assigned owners.",
    "   - Classify information according to sensitivity: Public, Internal, Confidential, Restricted.",
    "2. **Access Control (A.9)**",
    "   - Enforce least-privilege access based on business need.",
    "   - Conduct access reviews every 90 days.",
    "3. **Cryptography (A.10)**",
    "   - Encrypt data at rest and in transit using approved algorithms.",
    "   - Manage cryptographic keys with defined lifecycle procedures.",
    "4. **Incident Management (A.16)**",
    "   - Report security events within 1 hour of detection.",
    "   - Conduct post-incident reviews within 5 business days.",
    "",
    "## Risk Assessment",
    "- Conduct formal risk assessments annually and upon significant change.",
    "- Accept risks only when residual risk falls within the approved appetite.",
    "",
    "## Additional Context",
    "{{input.summary}}",
    "",
    "---",
    "*This document was generated deterministically by AtlasIT compliance automation.*",
    "",
  ].join("\n"),
};

const NIST_CSF_TEMPLATE: PolicyTemplateRecord = {
  key: "nist.csf",
  name: "NIST Cybersecurity Framework Policy",
  format: "markdown",
  body: [
    "# NIST Cybersecurity Framework Policy",
    "",
    "**Tenant:** {{tenantId}}",
    "",
    "**Generated:** {{generatedAt}}",
    "",
    "## Purpose",
    "This policy aligns {{tenantId}} cybersecurity practices with the NIST Cybersecurity Framework (CSF 2.0) core functions.",
    "",
    "## Scope",
    "- All IT systems, networks, and data under the control of {{tenantId}}",
    "- Cloud services, SaaS applications, and third-party integrations",
    "",
    "## Framework Functions",
    "",
    "### 1. GOVERN (GV)",
    "- Establish cybersecurity risk management strategy approved by leadership.",
    "- Define roles, responsibilities, and authorities for cybersecurity.",
    "",
    "### 2. IDENTIFY (ID)",
    "- Maintain current asset inventory including hardware, software, and data flows.",
    "- Perform annual business impact analysis for critical systems.",
    "- Identify supply chain risks for key vendors.",
    "",
    "### 3. PROTECT (PR)",
    "- Implement identity management with MFA for all privileged access.",
    "- Deploy endpoint protection and patch management within 14 days of release.",
    "- Conduct security awareness training quarterly.",
    "",
    "### 4. DETECT (DE)",
    "- Monitor systems continuously with SIEM or equivalent tooling.",
    "- Establish baseline behavior profiles and alert on anomalies.",
    "- Review detection effectiveness monthly.",
    "",
    "### 5. RESPOND (RS)",
    "- Activate incident response plan within 30 minutes of confirmed incident.",
    "- Communicate with stakeholders per the notification matrix.",
    "- Contain threats and preserve forensic evidence.",
    "",
    "### 6. RECOVER (RC)",
    "- Execute recovery procedures to restore services within defined RTO/RPO.",
    "- Conduct lessons-learned review within 10 business days.",
    "- Update recovery plans based on findings.",
    "",
    "## Roles & Responsibilities",
    "- **CISO / Security Lead:** {{input.contactEmail}}",
    "- **Review Cadence:** Semi-annually with ad-hoc updates post-incident",
    "",
    "## Additional Context",
    "{{input.summary}}",
    "",
    "---",
    "*This document was generated deterministically by AtlasIT compliance automation.*",
    "",
  ].join("\n"),
};

const HIPAA_TEMPLATE: PolicyTemplateRecord = {
  key: "hipaa.security",
  name: "HIPAA Security Rule Compliance Policy",
  format: "markdown",
  body: [
    "# HIPAA Security Rule Compliance Policy",
    "",
    "**Tenant:** {{tenantId}}",
    "",
    "**Generated:** {{generatedAt}}",
    "",
    "## Purpose",
    "This policy ensures {{tenantId}} compliance with the HIPAA Security Rule (45 CFR Part 160 and Part 164, Subparts A and C) for the protection of electronic Protected Health Information (ePHI).",
    "",
    "## Scope",
    "- All systems that create, receive, maintain, or transmit ePHI",
    "- Workforce members and business associates with ePHI access",
    "",
    "## Administrative Safeguards",
    "1. **Security Management Process**",
    "   - Conduct risk analysis annually and document findings.",
    "   - Implement risk management measures to reduce vulnerabilities.",
    "2. **Workforce Security**",
    "   - Verify authorization before granting ePHI access.",
    "   - Terminate access within 24 hours of role change or departure.",
    "3. **Security Awareness Training**",
    "   - Deliver HIPAA security training at hire and annually thereafter.",
    "   - Conduct phishing simulations quarterly.",
    "",
    "## Physical Safeguards",
    "1. **Facility Access Controls**",
    "   - Restrict physical access to areas housing ePHI systems.",
    "   - Maintain visitor logs and escort policies.",
    "2. **Workstation & Device Security**",
    "   - Encrypt all portable devices storing ePHI.",
    "   - Implement automatic screen lock after 5 minutes of inactivity.",
    "",
    "## Technical Safeguards",
    "1. **Access Controls**",
    "   - Assign unique user IDs for all ePHI system access.",
    "   - Implement emergency access procedures.",
    "2. **Audit Controls**",
    "   - Log all access to ePHI with timestamps and user identity.",
    "   - Review audit logs monthly for unauthorized access.",
    "3. **Transmission Security**",
    "   - Encrypt ePHI in transit using TLS 1.2 or higher.",
    "   - Implement integrity controls to verify data has not been altered.",
    "",
    "## Roles & Responsibilities",
    "- **HIPAA Security Officer:** {{input.contactEmail}}",
    "- **Privacy Officer:** Coordinates with Security Officer on breach response",
    "- **Review Cadence:** Annually with updates upon regulatory changes",
    "",
    "## Additional Context",
    "{{input.summary}}",
    "",
    "---",
    "*This document was generated deterministically by AtlasIT compliance automation.*",
    "",
  ].join("\n"),
};

const DATA_PROTECTION_TEMPLATE: PolicyTemplateRecord = {
  key: "dataprotection.general",
  name: "Data Protection & Privacy Policy",
  format: "markdown",
  body: [
    "# Data Protection & Privacy Policy",
    "",
    "**Tenant:** {{tenantId}}",
    "",
    "**Generated:** {{generatedAt}}",
    "",
    "## Purpose",
    "This policy governs how {{tenantId}} collects, processes, stores, and disposes of personal data in compliance with applicable data protection regulations.",
    "",
    "## Scope",
    "- All personal data processed by {{tenantId}} regardless of format",
    "- All departments, employees, contractors, and data processors",
    "",
    "## Data Protection Principles",
    "1. **Lawfulness & Transparency:** Process personal data lawfully with clear privacy notices.",
    "2. **Purpose Limitation:** Collect data only for specified, explicit, and legitimate purposes.",
    "3. **Data Minimization:** Process only the minimum data necessary for each purpose.",
    "4. **Accuracy:** Keep personal data accurate and up to date.",
    "5. **Storage Limitation:** Retain data only as long as necessary for its purpose.",
    "6. **Integrity & Confidentiality:** Protect data with appropriate security measures.",
    "",
    "## Data Subject Rights",
    "- Right of access: Respond within 30 days of request.",
    "- Right to rectification: Correct inaccurate data without undue delay.",
    "- Right to erasure: Delete data when no longer necessary or upon valid request.",
    "- Right to data portability: Provide data in machine-readable format upon request.",
    "",
    "## Data Processing",
    "- Maintain a Record of Processing Activities (ROPA).",
    "- Conduct Data Protection Impact Assessments for high-risk processing.",
    "- Execute Data Processing Agreements with all third-party processors.",
    "",
    "## Breach Notification",
    "- Report breaches to the supervisory authority within 72 hours.",
    "- Notify affected data subjects without undue delay when risk is high.",
    "- Document all breaches regardless of notification requirement.",
    "",
    "## Roles & Responsibilities",
    "- **Data Protection Officer:** {{input.contactEmail}}",
    "- **Data Owners:** Department heads accountable for data within their function",
    "- **Review Cadence:** Annually and upon regulatory changes",
    "",
    "## Additional Context",
    "{{input.summary}}",
    "",
    "---",
    "*This document was generated deterministically by AtlasIT compliance automation.*",
    "",
  ].join("\n"),
};

export const DEFAULT_POLICY_TEMPLATES: PolicyTemplateRecord[] = [
  SOC2_TEMPLATE,
  ISO27001_TEMPLATE,
  NIST_CSF_TEMPLATE,
  HIPAA_TEMPLATE,
  DATA_PROTECTION_TEMPLATE,
];
