# Minimal kubeconfig template
apiVersion: v1
kind: Config
clusters:
- name: atlasit-dev
  cluster:
    server: https://CHANGE_ME_API_SERVER
    certificate-authority-data: CHANGE_ME_BASE64_CA
contexts:
- name: atlasit-dev
  context:
    cluster: atlasit-dev
    user: atlasit-dev-user
current-context: atlasit-dev
users:
- name: atlasit-dev-user
  user:
    token: CHANGE_ME_BEARER_TOKEN
