name = "atlasit-core-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
account_id = "620865722bd88ef0a77dbbb60c91392e"

[[d1_databases]]
binding = "DB"
database_name = "atlasit-shared"
database_id = "4c219864-76be-4453-a494-a4e0904e9cbc"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "c3017a1a156a4f2fa2da62dadc714c44"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "4f08086308004796bfd7cab01c34b006"

[[kv_namespaces]]
binding = "KV_FEATURE_FLAGS"
id = "6a94dc4144f04b82a4989677c47509da"

[env.dev]
name = "atlasit-core-api-dev"
workers_dev = true

[env.dev.vars]
ENVIRONMENT = "development"

[env.staging]
name = "atlasit-core-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "atlasit-core-api"
routes = ["api.atlasit.pro/api/*", "api.atlasit.pro/health"]

[env.production.vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true
