export {
  AuthModelSchema,
  OAuth2ConfigSchema,
  ApiKeyConfigSchema,
  AuthConfigSchema,
  CapabilitySchema,
  ConfigFieldSchema,
  WebhookEndpointSchema,
  ConnectorManifestSchema,
  type AuthModel,
  type OAuth2Config,
  type ApiKeyConfig,
  type AuthConfig,
  type Capability,
  type ConfigField,
  type WebhookEndpoint,
  type ConnectorManifest,
} from "./manifest.js";

export {
  validateManifest,
  validateConfigValues,
  type ValidationResult,
} from "./validation.js";

export {
  SLACK_MANIFEST,
  GOOGLE_WORKSPACE_MANIFEST,
  OKTA_MANIFEST,
  MICROSOFT_365_MANIFEST,
  JIRA_MANIFEST,
  CONFLUENCE_MANIFEST,
  QUICKBOOKS_MANIFEST,
  XERO_MANIFEST,
  ZOOM_MANIFEST,
  TEAMS_MANIFEST,
  DISCORD_MANIFEST,
  BAMBOOHR_MANIFEST,
  WORKDAY_MANIFEST,
  ADP_MANIFEST,
  STRIPE_MANIFEST,
  AUTH0_MANIFEST,
  CROWDSTRIKE_MANIFEST,
  ONEPASSWORD_MANIFEST,
  PAGERDUTY_MANIFEST,
  DATADOG_MANIFEST,
  AWS_MANIFEST,
  GCP_MANIFEST,
  AZURE_MANIFEST,
  GITHUB_MANIFEST,
  ALL_MANIFESTS,
} from "./templates.js";
