name = "ignite-ai-orchestrator"
main = "index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# KV Namespace for task tracking
[[kv_namespaces]]
binding = "TASKS"
id = "fa174a1795c94a48b47c22d6a138de29"
preview_id = "091c0fba72c84433b9fa0a453b1181ba"

[env.production]
usage_model = "bundled"
vars = { ENVIRONMENT = "production" }

[env.production.logs]
enabled = true 