name = "slack-approval-worker"
main = "index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[env.production]
route = "slack-approval.atlasit.workers.dev/*"
usage_model = "bundled"

[env.production.vars]
SLACK_SIGNING_SECRET = ""  # Set this via wrangler secret 