name = "atlasit-docs" # previously ignite-documentation
main = "index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for documentation
[[kv_namespaces]]
binding = "DOCS"
id = "88514b613c2e4721a358352752580d65"
preview_id = "f8c916deeae240f0825097e3b7d17214"

# Production environment
[env.production]
# New canonical route (legacy: docs.project-ignite.workers.dev)
route = "docs.atlasit.workers.dev/*"
usage_model = "bundled"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "DOCS"
id = "88514b613c2e4721a358352752580d65"

[env.production.logs]
enabled = true
