// AUTO-GENERATED by generate-registry.mjs — do not edit by hand
import type { CdtEvent } from "./models.js";
import { evalGDPR_Art5_1a } from "./rules/gdpr.art5_1a.js";
import { evalGDPR_Art5_1b } from "./rules/gdpr.art5_1b.js";
import { evalGDPR_Art5_1c } from "./rules/gdpr.art5_1c.js";
import { evalGDPR_Art5_1d } from "./rules/gdpr.art5_1d.js";
import { evalGDPR_Art5_1e } from "./rules/gdpr.art5_1e.js";
import { evalGDPR_Art5_1f } from "./rules/gdpr.art5_1f.js";
import { evalGDPR_Art5_2 } from "./rules/gdpr.art5_2.js";
import { evalHIPAA_164_312_a1 } from "./rules/hipaa.164_312_a1.js";
import { evalHIPAA_164_312_a2i } from "./rules/hipaa.164_312_a2i.js";
import { evalHIPAA_164_312_a2ii } from "./rules/hipaa.164_312_a2ii.js";
import { evalHIPAA_164_312_a2iv } from "./rules/hipaa.164_312_a2iv.js";
import { evalHIPAA_164_312_b } from "./rules/hipaa.164_312_b.js";
import { evalHIPAA_164_312_c1 } from "./rules/hipaa.164_312_c1.js";
import { evalHIPAA_164_312_d } from "./rules/hipaa.164_312_d.js";
import { evalISO_A12_6_1 } from "./rules/iso.a12_6_1.js";
import { evalISO_A13_1_1 } from "./rules/iso.a13_1_1.js";
import { evalISO_A16_1_1 } from "./rules/iso.a16_1_1.js";
import { evalISO_A16_1_2 } from "./rules/iso.a16_1_2.js";
import { evalISO_A16_1_4 } from "./rules/iso.a16_1_4.js";
import { evalISO_A5_1_1 } from "./rules/iso.a5_1_1.js";
import { evalISO_A9_1_1 } from "./rules/iso.a9_1_1.js";
import { evalISO_A9_1_2 } from "./rules/iso.a9_1_2.js";
import { evalISO_A9_2_1 } from "./rules/iso.a9_2_1.js";
import { evalISO_A9_2_2 } from "./rules/iso.a9_2_2.js";
import { evalISO_A9_2_3 } from "./rules/iso.a9_2_3.js";
import { evalISO_A9_2_4 } from "./rules/iso.a9_2_4.js";
import { evalISO_A9_2_5 } from "./rules/iso.a9_2_5.js";
import { evalISO_A9_2_6 } from "./rules/iso.a9_2_6.js";
import { evalISO_A9_3_1 } from "./rules/iso.a9_3_1.js";
import { evalISO_A9_4_1 } from "./rules/iso.a9_4_1.js";
import { evalISO_A9_4_2 } from "./rules/iso.a9_4_2.js";
import { evalNIST_DE_CM_1 } from "./rules/nist.de_cm_1.js";
import { evalNIST_PR_AC_1 } from "./rules/nist.pr_ac_1.js";
import { evalNIST_PR_AC_3 } from "./rules/nist.pr_ac_3.js";
import { evalNIST_PR_AC_4 } from "./rules/nist.pr_ac_4.js";
import { evalNIST_PR_AC_7 } from "./rules/nist.pr_ac_7.js";
import { evalNIST_PR_IP_3 } from "./rules/nist.pr_ip_3.js";
import { evalNIST_RS_CO_2 } from "./rules/nist.rs_co_2.js";
import { evalSOC2_CC1_1 } from "./rules/soc2.cc1_1.js";
import { evalSOC2_CC1_2 } from "./rules/soc2.cc1_2.js";
import { evalSOC2_CC1_3 } from "./rules/soc2.cc1_3.js";
import { evalSOC2_CC2_1 } from "./rules/soc2.cc2_1.js";
import { evalSOC2_CC2_2 } from "./rules/soc2.cc2_2.js";
import { evalSOC2_CC3_1 } from "./rules/soc2.cc3_1.js";
import { evalSOC2_CC3_2 } from "./rules/soc2.cc3_2.js";
import { evalSOC2_CC4_1 } from "./rules/soc2.cc4_1.js";
import { evalSOC2_CC4_2 } from "./rules/soc2.cc4_2.js";
import { evalSOC2_CC5_1 } from "./rules/soc2.cc5_1.js";
import { evalSOC2_CC5_2 } from "./rules/soc2.cc5_2.js";
import { evalSOC2_CC5_3 } from "./rules/soc2.cc5_3.js";
import { evalSOC2_CC6_1 } from "./rules/soc2.cc6_1.js";
import { evalSOC2_CC6_2 } from "./rules/soc2.cc6_2.js";
import { evalSOC2_CC6_3 } from "./rules/soc2.cc6_3.js";
import { evalSOC2_CC6_6 } from "./rules/soc2.cc6_6.js";
import { evalSOC2_CC6_7 } from "./rules/soc2.cc6_7.js";
import { evalSOC2_CC6_8 } from "./rules/soc2.cc6_8.js";
import { evalSOC2_CC7_1 } from "./rules/soc2.cc7_1.js";
import { evalSOC2_CC7_2 } from "./rules/soc2.cc7_2.js";
import { evalSOC2_CC7_3 } from "./rules/soc2.cc7_3.js";
import { evalSOC2_CC7_4 } from "./rules/soc2.cc7_4.js";
import { evalSOC2_CC7_5 } from "./rules/soc2.cc7_5.js";
import { evalSOC2_CC8_1 } from "./rules/soc2.cc8_1.js";
import { evalSOC2_CC9_1 } from "./rules/soc2.cc9_1.js";
import { evalSOC2_CC9_2 } from "./rules/soc2.cc9_2.js";

export type RuleDecision = {
  decision: "pass" | "fail" | "unknown";
  rationale: string[];
  references: string[];
};
export type ControlRule = {
  fn: (ev: CdtEvent) => RuleDecision;
  framework: string;
  pack: string;
  title: string;
};

export const CONTROL_REGISTRY: Record<string, ControlRule> = {
  "GDPR-Art5.1a": {
    fn: evalGDPR_Art5_1a,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Lawfulness, Fairness, Transparency",
  },
  "GDPR-Art5.1b": {
    fn: evalGDPR_Art5_1b,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Purpose Limitation",
  },
  "GDPR-Art5.1c": {
    fn: evalGDPR_Art5_1c,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Data Minimisation",
  },
  "GDPR-Art5.1d": {
    fn: evalGDPR_Art5_1d,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Accuracy",
  },
  "GDPR-Art5.1e": {
    fn: evalGDPR_Art5_1e,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Storage Limitation",
  },
  "GDPR-Art5.1f": {
    fn: evalGDPR_Art5_1f,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Integrity & Confidentiality",
  },
  "GDPR-Art5.2": {
    fn: evalGDPR_Art5_2,
    framework: "GDPR",
    pack: "pack-gdpr-builtin",
    title: "Accountability",
  },
  "HIPAA-164.312.a1": {
    fn: evalHIPAA_164_312_a1,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Access Control — Unique User Identification",
  },
  "HIPAA-164.312.a2i": {
    fn: evalHIPAA_164_312_a2i,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Emergency Access Procedure",
  },
  "HIPAA-164.312.a2ii": {
    fn: evalHIPAA_164_312_a2ii,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Automatic Logoff",
  },
  "HIPAA-164.312.a2iv": {
    fn: evalHIPAA_164_312_a2iv,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Encryption & Decryption",
  },
  "HIPAA-164.312.b": {
    fn: evalHIPAA_164_312_b,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Audit Controls",
  },
  "HIPAA-164.312.c1": {
    fn: evalHIPAA_164_312_c1,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Integrity Controls",
  },
  "HIPAA-164.312.d": {
    fn: evalHIPAA_164_312_d,
    framework: "HIPAA Security Rule",
    pack: "pack-hipaa-builtin",
    title: "Person or Entity Authentication",
  },
  "ISO-A12.6.1": {
    fn: evalISO_A12_6_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Management of Technical Vulnerabilities",
  },
  "ISO-A13.1.1": {
    fn: evalISO_A13_1_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Network Controls",
  },
  "ISO-A16.1.1": {
    fn: evalISO_A16_1_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Incident Response Responsibilities",
  },
  "ISO-A16.1.2": {
    fn: evalISO_A16_1_2,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Reporting Information Security Events",
  },
  "ISO-A16.1.4": {
    fn: evalISO_A16_1_4,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Assessment of Security Events",
  },
  "ISO-A5.1.1": {
    fn: evalISO_A5_1_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Information Security Policies",
  },
  "ISO-A9.1.1": {
    fn: evalISO_A9_1_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Access Control Policy",
  },
  "ISO-A9.1.2": {
    fn: evalISO_A9_1_2,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Access to Networks & Network Services",
  },
  "ISO-A9.2.1": {
    fn: evalISO_A9_2_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "User Registration & De-registration",
  },
  "ISO-A9.2.2": {
    fn: evalISO_A9_2_2,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "User Access Provisioning",
  },
  "ISO-A9.2.3": {
    fn: evalISO_A9_2_3,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Privileged Access Rights",
  },
  "ISO-A9.2.4": {
    fn: evalISO_A9_2_4,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Management of Secret Authentication",
  },
  "ISO-A9.2.5": {
    fn: evalISO_A9_2_5,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Review of User Access Rights",
  },
  "ISO-A9.2.6": {
    fn: evalISO_A9_2_6,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Removal/Adjustment of Access Rights",
  },
  "ISO-A9.3.1": {
    fn: evalISO_A9_3_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Use of Secret Authentication Information",
  },
  "ISO-A9.4.1": {
    fn: evalISO_A9_4_1,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Information Access Restriction",
  },
  "ISO-A9.4.2": {
    fn: evalISO_A9_4_2,
    framework: "ISO 27001:2022",
    pack: "pack-iso27001-builtin",
    title: "Secure Log-on Procedures",
  },
  "NIST-DE.CM-1": {
    fn: evalNIST_DE_CM_1,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Network Monitored for Events",
  },
  "NIST-PR.AC-1": {
    fn: evalNIST_PR_AC_1,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Identities & Credentials Managed",
  },
  "NIST-PR.AC-3": {
    fn: evalNIST_PR_AC_3,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Remote Access Managed",
  },
  "NIST-PR.AC-4": {
    fn: evalNIST_PR_AC_4,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Access Permissions & Authorizations",
  },
  "NIST-PR.AC-7": {
    fn: evalNIST_PR_AC_7,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Users/Devices/Assets Authenticated",
  },
  "NIST-PR.IP-3": {
    fn: evalNIST_PR_IP_3,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Configuration Change Control",
  },
  "NIST-RS.CO-2": {
    fn: evalNIST_RS_CO_2,
    framework: "NIST CSF 2.0",
    pack: "pack-nist-csf-builtin",
    title: "Incidents Reported",
  },
  "SOC2-CC1.1": {
    fn: evalSOC2_CC1_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Control Environment — Integrity & Ethics",
  },
  "SOC2-CC1.2": {
    fn: evalSOC2_CC1_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Board Independence & Oversight",
  },
  "SOC2-CC1.3": {
    fn: evalSOC2_CC1_3,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Management Authority & Responsibility",
  },
  "SOC2-CC2.1": {
    fn: evalSOC2_CC2_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Internal Communication of Objectives",
  },
  "SOC2-CC2.2": {
    fn: evalSOC2_CC2_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "External Communication of Objectives",
  },
  "SOC2-CC3.1": {
    fn: evalSOC2_CC3_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Risk Assessment — Objectives Specified",
  },
  "SOC2-CC3.2": {
    fn: evalSOC2_CC3_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Risk Identification & Analysis",
  },
  "SOC2-CC4.1": {
    fn: evalSOC2_CC4_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Control Activities — Selected & Developed",
  },
  "SOC2-CC4.2": {
    fn: evalSOC2_CC4_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Control Activities — Deployed Through Policies",
  },
  "SOC2-CC5.1": {
    fn: evalSOC2_CC5_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Control Activities Over Technology",
  },
  "SOC2-CC5.2": {
    fn: evalSOC2_CC5_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Policies & Procedures Established",
  },
  "SOC2-CC5.3": {
    fn: evalSOC2_CC5_3,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Policies Deployed Through Management",
  },
  "SOC2-CC6.1": {
    fn: evalSOC2_CC6_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Logical Access — Least Privilege",
  },
  "SOC2-CC6.2": {
    fn: evalSOC2_CC6_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "New User Access Authorization",
  },
  "SOC2-CC6.3": {
    fn: evalSOC2_CC6_3,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Role-Based Access Modification",
  },
  "SOC2-CC6.6": {
    fn: evalSOC2_CC6_6,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "External Access Points Protected",
  },
  "SOC2-CC6.7": {
    fn: evalSOC2_CC6_7,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Data Transmission Protection",
  },
  "SOC2-CC6.8": {
    fn: evalSOC2_CC6_8,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Prevention of Unauthorized Software",
  },
  "SOC2-CC7.1": {
    fn: evalSOC2_CC7_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Detection of Configuration Changes",
  },
  "SOC2-CC7.2": {
    fn: evalSOC2_CC7_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Monitoring System Components",
  },
  "SOC2-CC7.3": {
    fn: evalSOC2_CC7_3,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Security Event Evaluation",
  },
  "SOC2-CC7.4": {
    fn: evalSOC2_CC7_4,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Security Incident Response",
  },
  "SOC2-CC7.5": {
    fn: evalSOC2_CC7_5,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Recovery from Security Incidents",
  },
  "SOC2-CC8.1": {
    fn: evalSOC2_CC8_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Change Management Process",
  },
  "SOC2-CC9.1": {
    fn: evalSOC2_CC9_1,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Business Disruption Risk Mitigation",
  },
  "SOC2-CC9.2": {
    fn: evalSOC2_CC9_2,
    framework: "SOC 2 Type II",
    pack: "pack-soc2-builtin",
    title: "Vendor & Business Partner Management",
  },
};

export function listControls(): Array<{
  controlId: string;
  framework: string;
  pack: string;
  title: string;
}> {
  return Object.entries(CONTROL_REGISTRY).map(([controlId, c]) => ({
    controlId,
    framework: c.framework,
    pack: c.pack,
    title: c.title,
  }));
}

export function evaluate(controlId: string, ev: CdtEvent): RuleDecision | null {
  const rule = CONTROL_REGISTRY[controlId];
  if (!rule) return null;
  return rule.fn(ev);
}
